import React from "react";

const LandingPage = () => {

  return (
    <div className="landing-page">
      <h1>Who We Are</h1>
      <p id='paragraph-1'>We at Rolsa Tech believe that the transition to sustainable energy should be accessible, efficient, and seamless for every homeowner. Our journey began with a simple vision: to create integrated green energy solutions that work together harmoniously while empowering our customers to take control of their energy future. We've developed our solar panel technology with both performance and adaptability in mind, engineering proprietary high-efficiency photovoltaic cells that deliver exceptional output even in challenging weather conditions. We're particularly proud of our modular design approach, which allows our customers to start their solar journey according to their current needs and budget, with the flexibility to expand their systems over time. Our confidence in our products is reflected in our industry-leading 25-year warranty—we stand behind our technology because we know it's built to last.</p>
      <p id="paragraph-2">We've revolutionized the EV charging experience through our innovative bidirectional charging technology, transforming electric vehicles from mere transportation into valuable components of a home's energy ecosystem. Our adaptive charging algorithms represent years of research and development, intelligently managing power flow based on multiple variables including grid capacity, electricity costs, and individual usage patterns. We take particular satisfaction in how our commercial charging solutions are helping businesses across the country transition their fleets to electric vehicles while providing valuable amenities for their employees and customers. Every time we see one of our charging stations installed at a workplace or shopping center, we know we're expanding the infrastructure needed to accelerate the adoption of electric vehicles nationwide.</p>
      <p id='paragraph-3'>We consider our smart home energy management system to be the culmination of our vision—the brain that coordinates all elements of a truly sustainable home. We've invested countless hours developing the AI that powers this system, teaching it to analyze and optimize energy flows throughout the home in real-time. When our customers open our mobile application and see their energy savings and reduced carbon footprint, we share in their sense of accomplishment. Every kilowatt-hour generated by our solar panels, every efficient charging session managed by our EV chargers, and every optimization performed by our energy management system brings us closer to our ultimate goal: a world where clean, renewable energy is the standard, not the exception. We aren't just selling products at Rolsa Tech—we're partnering with our customers to create a more sustainable future, one home at a time.</p>
    
    </div>
  );
}

export default LandingPage;